language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo:
  required

services:
  - memcached
  - mysql
  - mongodb

env:
  global:
    - TEST_BT_HOST=127.0.0.1 TEST_BT_PORT=11300 TEST_MC_HOST=127.0.0.1 TEST_MC_PORT=11211 TEST_AS_HOST=127.0.0.1 TEST_AS_PORT=3000
  matrix:
    - PHALCON_VERSION="2.0.9"
    - PHALCON_VERSION="2.0.8"
    - PHALCON_VERSION="2.0.7"
    - PHALCON_VERSION="2.0.6"
    - PHALCON_VERSION="2.0.5"
    - PHALCON_VERSION="2.0.4"

before_install:
  - bash tests/_ci/setup_beanstalkd.sh
  - beanstalkd -v
  - beanstalkd -l ${TEST_BT_HOST} -p ${TEST_BT_PORT} & # start queue listener
  - sleep 5 # give server some time to boot
  - cd $TRAVIS_BUILD_DIR
  - pecl channel-update pecl.php.net
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install yaml < /dev/null &)
  - pecl install mongo < /dev/null &
  - phpenv config-add tests/_ci/memcached.ini
  - wget -O aerospike-server.tgz http://aerospike.com/download/server/latest/artifact/tgz
  - tar xvzf aerospike-server.tgz
  - cp -f tests/_ci/aerospike.conf ./aerospike-server/share/etc
  - cd aerospike-server
  - mkdir instance1
  - ./bin/aerospike init --home instance1 --instance 1 --service-port ${TEST_AS_PORT}
  - cd instance1
  - sudo ./bin/aerospike start
  - ./bin/aerospike status
  - cd ../..
  - sleep 3 # give server some time to boot

install:
  - composer self-update
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b phalcon-v${PHALCON_VERSION}
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j4 > /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null)
  - php -r 'echo \Phalcon\Version::get()."\n";'
  - travis_retry composer install --prefer-source --no-interaction
  - travis_retry composer require aerospike/aerospike-client-php "*"
  - find vendor/aerospike/aerospike-client-php/ -name "*.sh" -exec chmod +x {} \;
  - cd vendor/aerospike/aerospike-client-php
  - sudo $(which composer) run-script post-install-cmd
  - cd ../../..
  - echo "extension=${TRAVIS_BUILD_DIR}/vendor/aerospike/aerospike-client-php/src/aerospike/modules/aerospike.so" | tee -a tests/_ci/aerospike.ini
  - phpenv config-add tests/_ci/aerospike.ini
  - php -m

before_script:
  - mysql -e 'create database incubator_tests charset=utf8mb4 collate=utf8mb4_unicode_ci;'

script:
  - vendor/bin/phpcs --standard=PSR2 --colors --extensions=php --encoding=utf-8 Library/
  - vendor/bin/codecept build
  - vendor/bin/codecept run --coverage-text

addons:
  apt:
    packages:
      - libyaml-dev
      - libssl-dev
      - autoconf

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
