language: php

env:
  - PHALCON_VERSION="2.0.0"
  - PHALCON_VERSION="1.3.5"
  - PHALCON_VERSION="1.3.4"
  - PHALCON_VERSION="1.3.3"
  - PHALCON_VERSION="1.3.2"
  - PHALCON_VERSION="1.3.1"

before_script:
  - ./tests/install-php-extension.sh ${PHALCON_VERSION}
  - php -r "echo Phalcon\Version::get()."\n";"
  - composer update

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 Library/
  - phpunit --configuration tests/phpunit.xml.dist
