language: php

env:
  - PHALCON_VERSION="phalcon-v2.0.3"
  - PHALCON_VERSION="phalcon-v2.0.2"
  - PHALCON_VERSION="phalcon-v2.0.1"
  - PHALCON_VERSION="phalcon-v2.0.0"

install:
  - tests/memcached.sh

before_script:
  - export HTTPS_PROXY_REQUEST_FULLURI=false
  - export HTTP_PROXY_REQUEST_FULLURI=true
  - composer self-update
  - ./tests/install-php-extension.sh ${PHALCON_VERSION}
  - php -r 'echo \Phalcon\Version::get()."\n";'
  - travis_wait composer update
  - mysql -e 'create database incubator_tests charset=utf8mb4 collate=utf8mb4_unicode_ci;'
  - mysql -uroot incubator_tests < tests/travis/db_schema.sql

php:
  - 5.4
  - 5.5
  - 5.6

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 Library/
  - phpunit --configuration tests/phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - mysql -e 'DROP DATABASE incubator_tests;' -uroot

services:
  - memcached
  - mysql
