language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: required
dist: trusty

before_install:
  - composer self-update
  - sudo service memcached stop
  - sudo service docker stop

install:
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --force-yes docker-engine
  - sudo service docker restart
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - travis_retry composer install --ignore-platform-reqs --prefer-source --no-interaction
  - travis_retry composer require --ignore-platform-reqs "duncan3dc/fork-helper:*"

before_script:
  - stty cols 160
  - docker-compose -p incubator up -d
  - sleep 5

script:
  - bash runtest.sh

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
